spring.application.name=mentimeter
spring.datasource.url=jdbc:postgresql://localhost:5432/polling_app
spring.datasource.username=ken
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true